/*
 * This file is generated by jOOQ.
 */
package com.github.prominence.arbaro.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = -1940156472;

    private final Integer id;
    private final String  role;

    public Role(Role value) {
        this.id = value.id;
        this.role = value.role;
    }

    public Role(
        Integer id,
        String  role
    ) {
        this.id = id;
        this.role = role;
    }

    public Integer getId() {
        return this.id;
    }

    public String getRole() {
        return this.role;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
