/*
 * This file is generated by jOOQ.
 */
package com.github.prominence.arbaro.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1649148291;

    private final Integer id;
    private final String  email;
    private final String  password;
    private final Boolean isactive;

    public User(User value) {
        this.id = value.id;
        this.email = value.email;
        this.password = value.password;
        this.isactive = value.isactive;
    }

    public User(
        Integer id,
        String  email,
        String  password,
        Boolean isactive
    ) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.isactive = isactive;
    }

    public Integer getId() {
        return this.id;
    }

    public String getEmail() {
        return this.email;
    }

    public String getPassword() {
        return this.password;
    }

    public Boolean getIsactive() {
        return this.isactive;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(isactive);

        sb.append(")");
        return sb.toString();
    }
}
