/*
 * This file is generated by jOOQ.
 */
package com.github.prominence.arbaro.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User2role implements Serializable {

    private static final long serialVersionUID = -2030597585;

    private final Integer id;
    private final Integer userId;
    private final Integer roleId;

    public User2role(User2role value) {
        this.id = value.id;
        this.userId = value.userId;
        this.roleId = value.roleId;
    }

    public User2role(
        Integer id,
        Integer userId,
        Integer roleId
    ) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User2role (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
