/*
 * This file is generated by jOOQ.
 */
package com.github.prominence.arbaro.db;


import com.github.prominence.arbaro.db.tables.Databasechangeloglock;
import com.github.prominence.arbaro.db.tables.Role;
import com.github.prominence.arbaro.db.tables.User;
import com.github.prominence.arbaro.db.tables.User2role;
import com.github.prominence.arbaro.db.tables.records.DatabasechangeloglockRecord;
import com.github.prominence.arbaro.db.tables.records.RoleRecord;
import com.github.prominence.arbaro.db.tables.records.User2roleRecord;
import com.github.prominence.arbaro.db.tables.records.UserRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = UniqueKeys0.DATABASECHANGELOGLOCK_PKEY;
    public static final UniqueKey<RoleRecord> ROLE_PKEY = UniqueKeys0.ROLE_PKEY;
    public static final UniqueKey<RoleRecord> ROLE_ROLE_KEY = UniqueKeys0.ROLE_ROLE_KEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;
    public static final UniqueKey<UserRecord> USER_EMAIL_KEY = UniqueKeys0.USER_EMAIL_KEY;
    public static final UniqueKey<User2roleRecord> USER2ROLE_PKEY = UniqueKeys0.USER2ROLE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<User2roleRecord, UserRecord> USER2ROLE__FK_USER_ID = ForeignKeys0.USER2ROLE__FK_USER_ID;
    public static final ForeignKey<User2roleRecord, RoleRecord> USER2ROLE__FK_ROLE_ID = ForeignKeys0.USER2ROLE__FK_ROLE_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, "databasechangeloglock_pkey", Databasechangeloglock.DATABASECHANGELOGLOCK.ID);
        public static final UniqueKey<RoleRecord> ROLE_PKEY = Internal.createUniqueKey(Role.ROLE, "role_pkey", Role.ROLE.ID);
        public static final UniqueKey<RoleRecord> ROLE_ROLE_KEY = Internal.createUniqueKey(Role.ROLE, "role_role_key", Role.ROLE.ROLE_);
        public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, "user_pkey", User.USER.ID);
        public static final UniqueKey<UserRecord> USER_EMAIL_KEY = Internal.createUniqueKey(User.USER, "user_email_key", User.USER.EMAIL);
        public static final UniqueKey<User2roleRecord> USER2ROLE_PKEY = Internal.createUniqueKey(User2role.USER2ROLE, "user2role_pkey", User2role.USER2ROLE.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<User2roleRecord, UserRecord> USER2ROLE__FK_USER_ID = Internal.createForeignKey(com.github.prominence.arbaro.db.Keys.USER_PKEY, User2role.USER2ROLE, "user2role__fk_user_id", User2role.USER2ROLE.USER_ID);
        public static final ForeignKey<User2roleRecord, RoleRecord> USER2ROLE__FK_ROLE_ID = Internal.createForeignKey(com.github.prominence.arbaro.db.Keys.ROLE_PKEY, User2role.USER2ROLE, "user2role__fk_role_id", User2role.USER2ROLE.ROLE_ID);
    }
}
