/*
 * This file is generated by jOOQ.
 */
package com.github.prominence.arbaro.db;


import com.github.prominence.arbaro.db.tables.Databasechangelog;
import com.github.prominence.arbaro.db.tables.Databasechangeloglock;
import com.github.prominence.arbaro.db.tables.Role;
import com.github.prominence.arbaro.db.tables.User;
import com.github.prominence.arbaro.db.tables.User2role;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user2role</code>.
     */
    public static final User2role USER2ROLE = User2role.USER2ROLE;
}
